name: Publish
on: [push]

jobs:
  pack:
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/texsnip
    permissions:
      id-token: write

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Fetch Python build dependencies
      run: python -m pip install --user wheel

    - name: Build
      run: python -m build

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        skip-existing: true
